### ISSUE TITLE
Possible to set a password to protect the write access ? 

### ISSUE THREAD

**Issue by shu-soleil** [PandABlocks/PandABlocks-webcontrol#5]
Hello, we're wondering if it would be possible to set a password to protect the write access from the web GUI interface ? 
Thanks

**Comment by coretl** [comment]
It might be possible, but doing it properly is difficult, and I don't want to put something out that promises "password protection", but is actually insecure.

What is the use case? To stop other staff members writing to PandA by accident? Or to stop extenal people connecting?

At DLS we treat PandA in the same way as PowerBrick and other embedded Devices, we hide it on a separate network so you can only access it on the beamline. This is sufficient for us.

**Comment by shu-soleil** [comment]
This is more to prevent accident writing if someone opens the GUI just for monitoring. Is it possible to have a read-only option by default ?

At SOLEIL the pandabox is also on the beamline separeted network so no external connecting issue.

**Comment by coretl** [comment]
There is one fairly easy option to add, we currently have a `WS` block, at the same level as the top level `PANDA` block.

![image](https://github.com/PandABlocks/PandABlocks-webcontrol/assets/101418278/aeaccbeb-604d-46a6-bee4-0f5806945234)

We can add some new parameters to it, `writeable`, which says whether PANDA is writeable at the moment, and `setWriteable(writeable: bool, duration: float)` which will be a button on the GUI that looks a bit like the save button:

![image](https://github.com/PandABlocks/PandABlocks-webcontrol/assets/101418278/581cca92-d720-4415-9917-d87996d9a4e9)

If you check `writeable` and set `duration` to 60, then the web GUI will be writeable for an hour, for *everyone*.

Does this sound reasonable?

**Comment by shu-soleil** [comment]
Sounds a good option if it doesn't bring too much work for you. lt could be very helpful. So the `writable` button will come with a `duration` parameter in second?
Thanks

**Comment by coretl** [comment]
Probably? Or in minutes? Or would you prefer just a simple toggle between writeable and read-only that you have to remember to press to make it read-only again when you're done?

**Comment by shu-soleil** [comment]
Sorry I meant "minute" actually, it's good for me

**Comment by coretl** [comment]
Actually, we might be able to be cleverer than this, and make it per session, then we can have a simple toggle. We will investigate, but not until 3.0 is out...

**Comment by coretl** [comment]
I think we can do this by inspecting the client name here:
https://github.com/dls-controls/pymalcolm/blob/408ab2b6fa4e2dd9c6cbc1a415d49688dc6a3df8/malcolm/modules/web/parts/websocketserverpart.py#L80

Then keeping an internal record of whether the client can write or not

**Comment by shu-soleil** [comment]
> Actually, we might be able to be cleverer than this, and make it per session, then we can have a simple toggle. We will investigate, but not until 3.0 is out...

Ok thanks

**Comment by tomtrafford** [comment]
This is not planned at the moment
