### ISSUE TITLE
Server doesn't start when a time attribute is set to "min"

### ISSUE THREAD

**Issue by coretl** [PandABlocks/PandABlocks-webcontrol#6]
This needs to be fixed in Malcolm

**Comment by tomtrafford** [comment]
Malcolm currently only allows the time units to be one of ["s", "ms", "us"].

**Comment by tomtrafford** [comment]
I have now added 'min' as an option in [Malcolm](https://github.com/dls-controls/pymalcolm/commit/006c1016d6a206bdb7cc9256e9a1175fd12ff294) . Future builds of the container should pick up this change automatically.
